import { Product } from 'src/entities';
import { faker } from '@faker-js/faker';

export const Mock_Product: Product[] = [
  {
    id: '01J8ZD1ES1APNTFH2F2ERVTNFC',
    productCode: 'ROOM-STD',
    name: 'Standard Room',
    description: 'Comfortable standard room with basic amenities',
    localDescription: 'Habitación estándar cómoda con servicios básicos',
    categoryId: 'CATEGORY-001',
    subCategoryId: 'SUBCAT-001',
    itemGroupId: 'GRP-ACCOM',
    primaryInventoryUnitId: 'UNIT-NIGHT',
    size: 'Single',
    color: 'Neutral',
    barcode: '1234567890123',
    isActive: true,
    basePrice: 100,
    currencyId: 'CURRENCY-ID',
    taxType: 'VAT',
    taxRate: 10,
    standardCost: 80,
    lastCost: 80,
    priceDeviationLimit: 20,
    quantityDeviationLimit: 5,
    minStockLevel: 1,
    maxStockLevel: 50,
    isForSale: true,
    isIngredient: false,
    weight: 0,

    shelfLife: 0,
    storageInstructions: 'N/A',
    imageUrl: 'https://example.com/standard-room.jpg',
    preferVendor: 'N/A',
    create_On: faker.date.past({ refDate: new Date() }),
    update_On: faker.date.past({ refDate: new Date() }),
    price: 0,
  },
  {
    id: '01J8ZD1ES1587196BQ5C7M95K6',
    productCode: 'ROOM-DLX',
    name: 'Deluxe Room',
    description: 'Spacious deluxe room with premium amenities',
    localDescription: 'Habitación de lujo espaciosa con servicios premium',
    categoryId: 'CAT-ROOM',
    subCategoryId: 'SUBCAT-DLX',
    itemGroupId: 'GRP-ACCOM',
    primaryInventoryUnitId: 'UNIT-NIGHT',
    size: 'Double',
    color: 'Neutral',
    barcode: '2345678901234',
    isActive: true,
    basePrice: 150,
    currencyId: 'USD',
    taxType: 'VAT',
    taxRate: 10,
    standardCost: 120,
    lastCost: 120,
    priceDeviationLimit: 30,
    quantityDeviationLimit: 5,
    minStockLevel: 1,
    maxStockLevel: 30,
    isForSale: true,
    isIngredient: false,
    weight: 0,
    shelfLife: 0,
    storageInstructions: 'N/A',
    imageUrl: 'https://example.com/deluxe-room.jpg',
    preferVendor: 'N/A',
    create_On: faker.date.past({ refDate: new Date() }),
    update_On: faker.date.past({ refDate: new Date() }),
    price: 0,
  },
  {
    id: '01J8ZD1ES1JVC4KGDPK2DKJ8TP',
    productCode: 'ROOM-STE',
    name: 'Suite',
    description: 'Luxurious suite with separate living area',
    localDescription: 'Suite lujosa con área de estar separada',
    categoryId: 'CAT-ROOM',
    subCategoryId: 'SUBCAT-STE',
    itemGroupId: 'GRP-ACCOM',
    primaryInventoryUnitId: 'UNIT-NIGHT',
    size: 'Suite',
    color: 'Neutral',
    barcode: '3456789012345',
    isActive: true,
    basePrice: 250,
    currencyId: 'USD',
    taxType: 'VAT',
    taxRate: 10,
    standardCost: 200,
    lastCost: 200,
    priceDeviationLimit: 50,
    quantityDeviationLimit: 3,
    minStockLevel: 1,
    maxStockLevel: 10,
    isForSale: true,
    isIngredient: false,
    weight: 0,
    shelfLife: 0,
    storageInstructions: 'N/A',
    imageUrl: 'https://example.com/suite.jpg',
    preferVendor: 'N/A',
    create_On: faker.date.past({ refDate: new Date() }),
    update_On: faker.date.past({ refDate: new Date() }),
    price: 0,
  },
  {
    id: '01J8ZD1ES17QP39V3ZJ491J03B',
    productCode: 'SVC-BRKFST',
    name: 'Breakfast Buffet',
    description: 'Full breakfast buffet service',
    localDescription: 'Servicio de desayuno buffet completo',
    categoryId: 'CAT-FOOD',
    subCategoryId: 'SUBCAT-BRKFST',
    itemGroupId: 'GRP-DINING',
    primaryInventoryUnitId: 'UNIT-PERSON',
    size: 'N/A',
    color: 'N/A',
    barcode: '4567890123456',
    isActive: true,
    basePrice: 25,
    currencyId: 'USD',
    taxType: 'VAT',
    taxRate: 10,
    standardCost: 15,
    lastCost: 15,
    priceDeviationLimit: 5,
    quantityDeviationLimit: 20,
    minStockLevel: 10,
    maxStockLevel: 100,
    isForSale: true,
    isIngredient: false,
    weight: 0,
    shelfLife: 0,
    storageInstructions: 'N/A',
    imageUrl: 'https://example.com/breakfast-buffet.jpg',
    preferVendor: 'N/A',
    create_On: faker.date.past({ refDate: new Date() }),
    update_On: faker.date.past({ refDate: new Date() }),
    price: 0,
  },
  {
    id: '01J8ZD1ES1YTYYWSKAKG11E9X5',
    productCode: 'SVC-WIFI',
    name: 'Wi-Fi Service',
    description: 'High-speed Wi-Fi internet access',
    localDescription: 'Acceso a internet Wi-Fi de alta velocidad',
    categoryId: 'CAT-SERVICE',
    subCategoryId: 'SUBCAT-INTERNET',
    itemGroupId: 'GRP-AMENITIES',
    primaryInventoryUnitId: 'UNIT-DAY',
    size: 'N/A',
    color: 'N/A',
    barcode: '5678901234567',
    isActive: true,
    basePrice: 10,
    currencyId: 'USD',
    taxType: 'VAT',
    taxRate: 10,
    standardCost: 5,
    lastCost: 5,
    priceDeviationLimit: 2,
    quantityDeviationLimit: 0,
    minStockLevel: 0,
    maxStockLevel: 0,
    isForSale: true,
    isIngredient: false,
    weight: 0,
    shelfLife: 0,
    storageInstructions: 'N/A',
    imageUrl: 'https://example.com/wifi-service.jpg',
    preferVendor: 'N/A',
    create_On: faker.date.past({ refDate: new Date() }),
    update_On: faker.date.past({ refDate: new Date() }),
    price: 0,
  },
];
