@host=http://localhost:4000


### Hello
GET {{host}}

### login
# @name login
POST {{host}}/api/v1/auth/login
Content-Type: application/json

{
    "username": "test1",
    "password": "password1"
}

# @access_token={{login.response.body.access_token}}

### register
POST {{host}}/api/v1/auth/register
content-type: application/json

{
    "email": "test@test.com",
    "password": "test"
}