export const API_URL = process.env.API_URL
export const tenantId = process.env.X_TENANT_ID
export const mockToken =
    `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA0MzhmZjQ0LTc1NGYtNDJiZC05NWI1LTUzYWFlMjBkZWMzZSIsInVzZXJuYW1lIjoidGVzdDEiLCJpYXQiOjE3MzAzNTg3MzAsImV4cCI6MTczMDM2MjMzMH0.fEQVPNRAyIkUqpPS981p6PJ1fJM_xStgKLEYtcyFV9U`